#!/usr/bin/env python3
"""Generate synthetic LLC-slice hash-chain probe tests."""

from __future__ import annotations

import argparse
from pathlib import Path


VARIANTS = [
    "skewed_bucket_reuse",
    "long_chain_miss",
    "short_chain_hit",
    "payload_heavy_emit",
    "phase_reuse",
    "evict_after_probe",
    "deep_prefetch",
    "small_tile_pressure",
    "wide_tile_pressure",
    "mixed_hit_miss",
]


def emit_case(case_id: int) -> str:
    variant = VARIANTS[(case_id - 1) % len(VARIANTS)]
    tile_bytes = 64 * (1 + ((case_id * 3) % 8))
    chain_depth = 2 + ((case_id * 5) % 15)
    stride = 1 + (case_id % 4)
    offset = 8 * (1 + ((case_id + 1) % 4))
    salt0 = 1103515245 + case_id * 2654435761
    salt1 = 97531 + case_id * 7919

    return f"""  // CASE {case_id:03d}: {variant}
  func.func @llc_slice_hash_join_case_{case_id:03d}(
      %buckets: !cira.handle<i64>,
      %keys: memref<?xi64>,
      %payloads: memref<?xi64>,
      %out: memref<?xi64>,
      %n: index
  ) attributes {{
    llc.case_id = {case_id} : i64,
    llc.variant = "{variant}",
    llc.tile_bytes = {tile_bytes} : i64,
    llc.chain_depth = {chain_depth} : i64,
    llc.next_offset = {offset} : i64
  }} {{
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %cstride = arith.constant {stride} : index
    %ctile = arith.constant {tile_bytes} : index
    %cdepth = arith.constant {chain_depth} : index
    %salt0 = arith.constant {salt0} : i64
    %salt1 = arith.constant {salt1} : i64
    %ht_buf = cira.alloc_cxl %ctile : !cira.handle<i64>
    %chain_f = cira.future_create : !cira.future<i64>
    %match_f = cira.future_create : !cira.future<i64>

    scf.for %i = %c0 to %n step %c1 {{
      %key = memref.load %keys[%i] : memref<?xi64>
      %payload = memref.load %payloads[%i] : memref<?xi64>
      %mix0 = arith.xori %key, %salt0 : i64
      %mix1 = arith.muli %mix0, %salt1 : i64
      %mix2 = arith.addi %mix1, %payload : i64

      cira.install_cacheline %buckets, %ctile level = 3 : !cira.handle<i64>, index
      cira.prefetch_indirect %buckets, offset = {offset}, depth = {chain_depth}
          : !cira.handle<i64>

      %ready = cira.future_await %chain_f : !cira.future<i64> -> i64
      %match0 = arith.cmpi eq, %ready, %key : i64
      scf.if %match0 {{
        %emit0 = arith.xori %mix2, %ready : i64
        memref.store %emit0, %out[%i] : memref<?xi64>
      }} else {{
        %miss0 = arith.addi %mix2, %salt0 : i64
        memref.store %miss0, %out[%i] : memref<?xi64>
      }}

      %tile_load = cira.load_async %ht_buf : !cira.handle<i64> -> !cira.future<i64>
      scf.for %j = %c0 to %cdepth step %c1 {{
        %j64 = arith.index_cast %j : index to i64
        %probe = arith.xori %mix2, %j64 : i64
        %store_f = cira.store_async %probe, %ht_buf
            : i64, !cira.handle<i64> -> !cira.future<i64>
        cira.flush
        cira.prefetch_stream %ht_buf, %ctile, stride = %cstride
            : !cira.handle<i64>, index

        %match_word = cira.future_await %match_f : !cira.future<i64> -> i64
        %hit = arith.cmpi eq, %match_word, %probe : i64
        scf.if %hit {{
          %emit1 = arith.addi %match_word, %payload : i64
          memref.store %emit1, %out[%i] : memref<?xi64>
        }}
      }}

      cira.evict_hint %ht_buf, %ctile : !cira.handle<i64>
      cira.barrier
    }}

    cira.phase_boundary "llc_slice_case_{case_id:03d}"
    cira.release %ht_buf : !cira.handle<i64>
    return
  }}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--cases", type=int, default=100)
    args = parser.parse_args()

    chunks = [
        "// Synthetic LLC-slice hash-chain probe corpus.",
        "// Generated by generate_llc_slice_synthetic.py.",
        "// RUN: cira %s --convert-cira-to-llvm-x86",
        "",
        "module {",
    ]
    chunks.extend(emit_case(case_id) for case_id in range(1, args.cases + 1))
    chunks.append("}")
    chunks.append("")

    args.output.write_text("\n".join(chunks), encoding="utf-8")


if __name__ == "__main__":
    main()
