//
// Created by yangyw on 8/5/24.
//

#include "Dialect/RemoteMemDialect.h"
#include "Dialect/CiraOps.h"
#include "Dialect/FunctionUtils.h"
#include "Dialect/OffloadOp.h"
#include "Dialect/RemoteMem.h"
#include "Dialect/RemoteMemRef.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/TypeSwitch.h"

using namespace mlir;
using namespace mlir::cira;

//===----------------------------------------------------------------------===//
// CIRA Type Definitions - Handle, Future, Stream (tablegen-generated)
//===----------------------------------------------------------------------===//

// Include the tablegen-generated type implementations
#define GET_TYPEDEF_CLASSES
#include "Dialect/RemoteMemTypes.cpp.inc"

// Register types and operations
void RemoteMemDialect::initialize() {
    registerTypes();

    // Register Cira operations
    addOperations<
#define GET_OP_LIST
#include "Dialect/CiraOps.cpp.inc"
        >();
}

void RemoteMemDialect::registerTypes() {
    // Register the RemoteMemRefType
    addTypes<RemoteMemRefType>();

    // Register new CIRA types: Handle, Future, Stream
    addTypes<HandleType, FutureType, StreamType>();
}

Attribute RemoteMemDialect::parseAttribute(DialectAsmParser &parser, Type type) const {
    // Basic attribute parsing - for now just return failure
    parser.emitError(parser.getNameLoc(), "custom attributes not supported yet");
    return {};
}

void RemoteMemDialect::printAttribute(Attribute attr, DialectAsmPrinter &printer) const {
    // Basic attribute printing - for now just emit error
    printer << "unknown_attr";
}

// parseType and printType are generated by tablegen in RemoteMemTypes.cpp.inc

// Include the generated dialect definitions
#include "Dialect/RemoteMemDialect.cpp.inc"